#!/usr/bin/env python

Import('env')


common_server = [
    "os_wiiu.cpp",
	# "audio_driver_psp.cpp",
	"rasterizer_wiiu.cpp",
	"mutex_wiiu.cpp",
	"thread_wiiu.cpp"
]

prog = env.Program('#bin/fe_wiiu', ['godot_wiiu.cpp'] + common_server)

env.Command(
 	"#FusionEngine.rpx", prog ,"elf2rpl bin/fe_wiiu.wiiu.opt.32 FusionEngine.rpx"
)
#
# env.Command(
# 	"#bin/strip.elf", "#bin/godot.elf" ,"psp-strip bin/godot.elf -o bin/strip.elf"
# )
#
# env.Command(
# 	"#bin/EBOOT.PBP", "#bin/strip.elf" ,"pack-pbp bin/EBOOT.PBP bin/PARAM.SFO NULL          NULL NULL NULL          NULL  bin/strip.elf NULL"
# )
